Format: expand pretty printer
ethereum/hevm pull request #348
Opened 2023-08-03 12:35 UTC by d-xo

## Description

Expand pretty printer to cover all cases. This currently produces output that is very newline heavy. Probably there is a smart way to teach it to print shorter expressions on one line only, but I think this is still a lot better than what we currently have.

## Checklist

- [x] tested locally
- [ ] added automated tests
- [ ] updated the docs
- [ ] updated the changelog

2023-08-08 12:50 UTC, msooseth commented on src/EVM/Format.hs
> +{-# LANGUAGE DataKinds #-}
```suggestion
```

2023-08-08 12:53 UTC, msooseth commented on src/EVM/Format.hs
> +      Max a b -> fmt "Min" [a, b]
```suggestion
      Max a b -> fmt "Max" [a, b]
```

2023-08-08 13:05 UTC, msooseth commented on src/EVM/Format.hs
> +  PLEq a b -> fmt "PGT" [a, b]
```suggestion
  PGEq a b -> fmt "PGEq" [a, b]
  PLEq a b -> fmt "PLEq" [a, b]
```

2023-08-08 13:17 UTC, msooseth requested changes
Really cool! I think there may be a few minor typos? I'm not sure of some were intentional, though :)

2023-08-08 21:52 UTC, d-xo commented
Thanks for spotting the typos! None were intentional 😬😅

2023-08-09 12:32 UTC, msooseth approved these changes
lgtm

2023-08-09 12:32 UTC, merged