Expr: correct oob case for symbolic branch in indexWord
ethereum/hevm pull request #59
Opened 2022-10-20 14:59 UTC by d-xo

## Description

Returning 0 on oob is actually the correct behaviour here: https://www.evm.codes/#1a?fork=arrowGlacier

## Checklist

- [x] tested locally
- [x] added automated tests
- [ ] updated the docs
- [ ] updated the changelog

2022-10-28 16:13 UTC, msooseth commented
I'd put a test case in just in case. BYTE should return 0, so we could have a test case like:

```
        testCase "check-asm-byte-oob" $ do
          Just c <- solcRuntime "C"
            [i|
            contract C {
              function foo(uint256 x) external pure {
                uint256 y;
                assembly { y := byte(32,x) }
                assert(y == 0);
              }
            }
            |]
          [Qed res] <- withSolvers Z3 1 $ \s -> checkAssert s defaultPanicCodes c (Just ("foo(uint256)", [AbiUIntType 256])) []
          putStrLn $ "Yes, we only get 0 back for any input"
        ,
```
We could even go fancy, and have `foo(uint256 x, uint256 x2)` and have an `if (x2 >= 32) { assembly { y := byte(x2,x)...}`, thereby proving it's correct for all oob access.

What do you think?

2022-10-28 16:14 UTC, msooseth requested changes
NICE CATCH! I'd like to have a test case as I mentioned in the comments, if that's OK? It should just copy-pate and work out of the box, I think? Let me know what you think!

2022-10-31 11:31 UTC, zoep approved these changes

2022-11-03 13:14 UTC, d-xo commented
Added a few more tests and also included an SMT encoding for symbolic word indexing. I let the existing concrete code paths in place since they resulted in a more direct encoding in SMT, but maybe it's worth simplifying the encoding logic at the expense of a more complex encoding.

2022-11-03 13:32 UTC, msooseth approved these changes
Looking good!

2022-11-03 13:52 UTC, d-xo commented
I think tests should pass here once the shl pr is merged

2022-11-03 16:20 UTC, merged